# Generated by Django 5.1.6 on 2025-02-21 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_alter_patient_address_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Only digits are allowed')]),
        ),
    ]
