# Generated by Django 5.1.6 on 2025-02-21 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_alter_patient_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +254712345678.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
