# Generated by Django 5.1.6 on 2025-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
