# Generated by Django 5.1.6 on 2025-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_department_labtest_alter_doctor_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='department',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
